services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
  
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  
  postgres:
    image: postgres:15
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgres/data
    environment:
      POSTGRES_USER: oshin
      POSTGRES_PASSWORD: passw0rd
      POSTGRES_DB: library

volumes:
  db:
    driver: local
